export const GET_USERS_REQUESTED= "GET_USERS_REQUESTED";
export const GET_USERS_SUCCEED= "GET_USERS_SUCCEED";
export const GET_USERS_FAILED= "GET_USERS_FAILED";

export const GET_POSTS_REQUESTED= "GET_POSTS_REQUESTED";
export const GET_POSTS_SUCCEED= "GET_POSTS_SUCCEED";
export const GET_POSTS_FAILED= "GET_POSTS_FAILED";